apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-app
  labels:
    app: falcon-app
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: falcon-app
  template:
    metadata:
      labels:
        app: falcon-app
    spec:
      containers:
      - name: falcon-app
        image: "bart3k1/falcon_app:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20

---          
apiVersion: v1
kind: Service
metadata:
  name: falcon-svc
  labels:
    app: falcon-app
spec:
  selector:
    app: falcon-app
  ports:
   - protocol: TCP
     port: 8000
     targetPort: 8000